### ISSUE TITLE
Reduce onboarding.bitshares.foundation registrar

### ISSUE THREAD

**Issue by froooze** [bitshares/committee-tools#10]
At the moment the onboarding.bitshares.foundation takes 15% as registrar. 
To stay competitive with OpenLedger the registrar should also be set to 0%.

Registrar cut was introduced to cover costs for signup, but with low signup costs and new referral system, this is not needed anymore.

**Comment by abitmore** [comment]
This topic is not for the committee to discuss or to take any action. Perhaps discuss in the worker thread in forum.

On the topic, setting registrar cut to 0% means the faucet won't have any income from new registered accounts, personally I don't think it's sustainable. By the way I don't know there is a "new referral system".
