### ISSUE TITLE
CREATE ASSET FEES

### ISSUE THREAD

**Issue by bitsharescrude** [bitshares/committee-tools#16]
**Currently Create asset fees have been increased by a whopping 1000%**
This pose a problem for small businesses and entrepreneurs who would love to create low risk tokens for projects or non-profit tokens for giveaways and memes. The solution of creating a one stop Token with subsequent price reduction for multiple.token is not enough.

Since the fee increase was as a result of the abuse of the low fee entry by rogue miscreants and fraudulent entities, I suggest that;
* The fees be reduced at least back to the previous amounts for Lifetime members especially the longer Symbols option.
*** Asset creation fees 
Longer Symbols: Lifetime Members 2413BTS/  Basic members 24130BTS***
* Or completely scrap the asset specific features for basic member and make it exclusive for LTMs
* Or create a above 10 or more symbol option that is cheaper
The asset create feature is a very important part of the BTS platform that gives it a competitive edge as a well known DEX in the cryptosphere, I appeal to the committee and those in charge to review urgently this fee increase and take appropriate corrective measures before the next core release scheduled in June.

**Comment by abitmore** [comment]
Note: this issue is due to https://github.com/bitshares/committee-tools/pull/15.

**Comment by abitmore** [comment]
@noblenobert wrote:
>The fees be reduced at least back to the previous amounts for Lifetime members especially the longer Symbols option.
Longer Symbols: Lifetime Members 2413BTS/ Basic members 24130BTS***

On one hand, I don't think 2413 BTS is a lot for businesses with proper plans.

On the other hand, I do think cheap multiple.token is the solution for businesses. It helps in recognition and branding for direct users of the BitShares platform. For indirect users, businesses can always remove the asset prefix from their own UI.

@noblenobert wrote:
> Or completely scrap the asset specific features for basic member and make it exclusive for LTMs
> Or create a above 10 or more symbol option that is cheaper

These are new features thus require a protocol upgrade (aka "hard fork"). It's better to discuss in https://github.com/bitshares/bsips.

**Comment by bitsharescrude** [comment]
> @noblenobert wrote:
> 
> > The fees be reduced at least back to the previous amounts for Lifetime members especially the longer Symbols option.
> > Longer Symbols: Lifetime Members 2413BTS/ Basic members 24130BTS***
> 
> On one hand, I don't think 2413 BTS is a lot for businesses with proper plans.
> 
> On the other hand, I do think cheap multiple.token is the solution for businesses. It helps in recognition and branding for direct users of the BitShares platform. For indirect users, businesses can always remove the asset prefix from their own UI.
> 
> @noblenobert wrote:
> 
> > Or completely scrap the asset specific features for basic member and make it exclusive for LTMs
> > Or create a above 10 or more symbol option that is cheaper
> 
> These are new features thus require a protocol upgrade (aka "hard fork"). It's better to discuss in https://github.com/bitshares/bsips.

Noted however it will be nice if the cheap.multiple token could be implemented ASAP

(edited by @abitmore for formatting)

**Comment by bitsharescrude** [comment]
> The bitshares-ui repository is not the best place to discuss individual fees. I'm transferring the issue to the committee-tools repository.

Noted

**Comment by abitmore** [comment]
The cheap multiple.token feature has been implemented for the 4.0 release. Please check the release notes: https://github.com/bitshares/bitshares-core/issues/2026.

**Comment by bitsharescrude** [comment]
> The cheap multiple.token feature has been implemented for the 4.0 release. Please check the release notes: [bitshares/bitshares-core#2026](https://github.com/bitshares/bitshares-core/issues/2026).

Ok that's good to know
