### ISSUE TITLE
Phishing account

### ISSUE THREAD

**Issue by bitsharescrude** [bitshares/committee-tools#22]
This account binanace-bts-1 is a phishing account, meant to steal funds of unsuspecting users please add it to the list
https://bts.ai/details/account/binanace-bts-1
I lost my funds to this account, it should be blacklisted

**Comment by abitmore** [comment]
Done.
https://github.com/bitshares/bitshares-ui/pull/3311
https://bts.ai/block/53718757

**Comment by bitsharescrude** [comment]
These accounts audio0audio and eliza85 are phishing accounts please blacklist

Here are a link of their nefarious activities
https://bts.ai/details/account/eliza85
https://bts.ai/details/account/audio0audio
