### ISSUE TITLE
Reduce Fee for Withdraw Vesting Balance

### ISSUE THREAD

**Issue by bangzi1001** [bitshares/committee-tools#7]
Since BitCNY and BitUSD market fee increase from 0.02%  to 0.1%, it have huge impact on market makers because they make profit/lose on tight spread. Their transaction volume is high per day with low profit margin. They need to maintain certain amounts of coins at both bid and ask side. 

A high Withdraw Vesting Balance fee (Standard Fee: 50.52054 BTS / Lifetime Member Fee: 10.10411 BTS )prevent them to bring back the coins to the market and make the order book look worse. I suggest the new fee for Withdraw Vesting Balance should same as Transfer Fee (Standard Fee: 0.45468 BTS BTS / Lifetime Member Fee: 0.09094 BTS )

**Comment by abitmore** [comment]
I agree with the proposed numbers.

Note that currently only LTMs have vesting balances from market fee sharing, they always pay LTM fee rate.

**Comment by thontron** [comment]
@abitmore Perhaps reference gui should scrap the "standard fee" then?

**Comment by abitmore** [comment]
@thontron I mentioned that because I want to enable market fee sharing for non-LTMs as well. See https://github.com/bitshares/bsips/issues/186.

**Comment by thontron** [comment]
@abitmore I see. I agree with you. This is a good place to give non-LTMs the incentive to interact more with the network.

**Comment by bitcrab** [comment]
agree

**Comment by abitmore** [comment]
Done.
